# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='compoDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='compoPartNum',
            new_name='PartNum',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='compoPrice',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='compoStock',
            new_name='Stock',
        ),
    ]
