# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlStock', '0002_auto_20180117_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='Datasheet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
